apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quarkus-app
    app.kubernetes.io/component: quarkus-app
    app.kubernetes.io/instance: quarkus-app
    app.kubernetes.io/name: quarkus-app
    app.kubernetes.io/part-of: quarkus-app
    app.openshift.io/runtime: quarkus
    app.openshift.io/runtime-namespace: project-100
  name: quarkus-app
  namespace: project-100
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: quarkus-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quarkus-app
        deployment: quarkus-app
    spec:
      containers:
      - image: quay.io/rhn_support_sreber/quarkus-app:latest
        imagePullPolicy: Always
        name: quarkus-app
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
