apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: quarkus-app-scaledobject
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          quarkus-app
  pollingInterval:  10
  cooldownPeriod:   300
  minReplicaCount:  1
  maxReplicaCount:  6
  fallback:
    failureThreshold: 3
    replicas: 1
  triggers:
    - type: prometheus
      metadata:
        serverAddress: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092
        namespace: project-100
        metricName: http_server_requests_seconds_count
        query: sum(rate(http_server_requests_seconds_count{job="quarkus-app"}[1m]))
        threshold: '1'
        ignoreNullValues: "true"
        authModes: "bearer"
      authenticationRef:
        name: quarkus-app-trigger
