apiVersion: v1
kind: Service
metadata:
  labels:
    app: quarkus-app
    app.kubernetes.io/component: quarkus-app
    app.kubernetes.io/instance: quarkus-app
    app.kubernetes.io/name: quarkus-app
    app.kubernetes.io/part-of: quarkus-app
    app.openshift.io/runtime-version: latest
  name: quarkus-app
  namespace: project-100
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: quarkus-app
    deployment: quarkus-app
  sessionAffinity: None
  type: ClusterIP
