apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: quarkus-app
  name: quarkus-app
  namespace: project-100
spec:
  endpoints:
  - interval: 30s
    path: /q/metrics
    scheme: http
    targetPort: 8080
  selector:
    matchLabels:
      app: quarkus-app
